### ISSUE TITLE
Not registered with NPM?

### ISSUE THREAD

**Issue by chadwatson** [40Digits/threepio#1]
``` bash
$ npm install threepio -g
npm ERR! 404 Not Found
```

**Comment by grantholle** [comment]
Yeah, I haven't published it yet until it was tested thoroughly. I put instructions in the slack channel:

Clone the repo locally. `cd` into the directory and run `npm i -g ./`

**Comment by grantholle** [comment]
It is now, https://www.npmjs.com/package/threepio
